version: "1"

services:
  web:
    build: .
    ports:
      - "8000:8031"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"